### ISSUE TITLE
Fix app detection as dialer app

### ISSUE THREAD

**Issue by fartem** [hash-checker/hash-checker-lite#15]
App must only opening from other apps for sharing files but not as default app or similar. Need attention to `intent-filter` sections in [AndroidManifest.xml](https://github.com/hash-checker/hash-checker-lite/blob/master/app/src/main/AndroidManifest.xml).

**Comment by jayagrawal254** [comment]
let me fix it.

**Comment by jayagrawal254** [comment]
Let me fix it.

**Comment by jayagrawal254** [comment]
Let me fix it

**Comment by fartem** [comment]
@jayagrawal254 Yes, you can fix it.
