### ISSUE TITLE
Add app closing with double tap on back button

### ISSUE THREAD

**Issue by fartem** [hash-checker/hash-checker-lite#16]
Right now you can exit from the app by tap on back button and press "Exit now" from showed bottom sheet. Replace this behaviour by exit from the application by double tap.

**Comment by jayagrawal254** [comment]
I will try it

**Comment by jayagrawal254** [comment]
I adding in my code in app/src/main/java/components/dialogs/system/ AppSnackbar.java 
is it correct

**Comment by jayagrawal254** [comment]
`private long backpressedTime;
        @override
        protected void onCreate(Bundle SavedInstanceState){
                super.onCreate(SavedInstanceState);
                setContentView(R.layout.activity_main);
        }

        @override
        public void onBackpressed()   {
                if(backpressedTime + 2000 > System.currentTimeMillis()){
                     super.onBackpressed();
                     return;
                }else{
                        Tost.makeText(getBaseContent(),"Press back again to exit",Tost.LENGTH_SHORT).show();
                }
        } `

**Comment by yasin459** [comment]
hello i would like to work on this issue

**Comment by fartem** [comment]
@yasin459 I'm assigned you to this issue.

**Comment by yasin459** [comment]
hello again .sorry but i have a problem in build, I get this error :
A problem occurred evaluating project ':app'.
> java.lang.NullPointerException (no error message)
i googled but I can't understand the problem, do you have any idea?

**Comment by yasin459** [comment]
@fartem can you help me please?

**Comment by fartem** [comment]
@yasin459 Of course. Can you tell me your answer?

**Comment by yasin459** [comment]
@fartem 
i have'nt done anything yet, i forked and cloned repo then tried to build for the first time(before making any changes)
then I confronted this error:

![image](https://user-images.githubusercontent.com/60640286/118151990-7684b700-b429-11eb-9d12-b2d5f677338f.png)

**Comment by fartem** [comment]
@yasin459 You need to add next lines to `local.properties` file in the root of the project:

```
RELEASE_KEYSTORE_PATH=''
RELEASE_KEYSTORE_PASSWORD=''
RELEASE_KEY_ALIAS=''
RELEASE_KEY_PASSWORD=''
```

When project building, Gradle read build config and configuration contains sign variables, than you should add to your Gradle settings (all variables is empty because they are using when you building `release` app version). But if you just run the app in `debug` flavor, this exception cannot be caused.

**Comment by vipozdn** [comment]
Need some help? If you are no longer working with this feature, please assign it to me
