### ISSUE TITLE
An error occurred during gradle syncing

### ISSUE THREAD

**Issue by vipozdn** [hash-checker/hash-checker-lite#50]
![gradle_issue](https://user-images.githubusercontent.com/32436953/116808727-1fd2cf80-ab43-11eb-8dc1-904d3884254e.png)

Changing System.getenv(KEYSTORE_PATH)
to String.valueOf(System.getenv(KEYSTORE_PATH))
solves the problem and makes a successful gradle sync

The same for the other three calls of System.getenv

If you accept this, assign it to me, please

**Comment by fartem** [comment]
Gradle send errors about this variables not declared. You need to add next lines in `local.properties` file in the project's root folder:

```gradle
RELEASE_KEYSTORE_PATH=''
RELEASE_KEYSTORE_PASSWORD=''
RELEASE_KEY_ALIAS=''
RELEASE_KEY_PASSWORD=''
```

Yes, variables can be empty because you cannot sign the app while run `debug` version.

**Comment by vipozdn** [comment]
> 
> 
> Gradle send errors about this variables not declared. You need to add next lines in `local.properties` file in the project's root folder:
> 
> ```groovy-gradle
> RELEASE_KEYSTORE_PATH=''
> RELEASE_KEYSTORE_PASSWORD=''
> RELEASE_KEY_ALIAS=''
> RELEASE_KEY_PASSWORD=''
> ```
> 
> Yes, variables can be empty because you cannot sign the app while run `debug` version.

Yes, before opening issue i tried to declare this values in local.properties. The error disappeared.
But look at repo's code:

```
if (keystoreProperties[KEYSTORE_PATH] == null) {
                keystoreProperties.put(
                        KEYSTORE_PATH,
                        System.getenv(KEYSTORE_PATH)
                )
   ...
}
```
In my understanding if keystoreProperties[KEYSTORE_PATH] == null (and it is actually null, coz KEYSTORE_PATH not declared in local.properties by default), then keystoreProperties.put() calls, which saves value System.getenv(KEYSTORE_PATH) with a key KEYSTORE_PATH at local.properties.
In theory, your code is built in such a way that you do not need to declare keys in local.properties.

I tried to figure out why this error occurred and found answer that you need to add String.valueOf() for result of System.getenv(KEYSTORE_PATH)

Now gradle error disappears and you don't even need to declare keys in local.properties. Your code already does it for you.

**Comment by fartem** [comment]
@vipozdn Thanks. Yes, this is works. I'm added value reading from ENV for CI. `local.properties` contains values only for current project, and if in ENV you are declared variable with same name but for another project, release build fails. CI (in the app case - GitHub Actions) has a separated environment.
