### ISSUE TITLE
Non-Free dependencies added with v1.0.8

### ISSUE THREAD

**Issue by IzzySoft** [hash-checker/hash-checker-lite#64]
**Describe the bug**
The last release added [Google Play Core](https://developer.android.com/guide/playcore) to the app. I'm not sure if it was accidentally dragged in as a dependency (which I hope is the case, as then you'd certainly be interested to get it out again) – or added on purpose?

**To Reproduce**
1. run `apktool d hash-checker-lite_1.0.8.apk`
2. dive into the created directory structure
3. find `/com/google/android/play/core`
4. Look shocked (or at least pretend) :speak_no_evil:

**Expected behavior**
No such thing there.

**Screenshots**
```
Libraries detected:
-------------------
* Android Support v4 (/android/support/v4): Development Framework
* AppCompat (/androidx/appcompat): Utility
* Constraint Layout Library (/androidx/constraintlayout): Utility
* Androidx Core (/androidx/core): Utility
* Lifecycle (/androidx/lifecycle): Utility
* Media (/androidx/media): Utility
* Preference (/androidx/preference): Utility
* Google Material Design (/com/google/android/material): Utility
* Google Play Core (/com/google/android/play/core): Utility NonFreeNet,NonFreeDep

Offending libs:
---------------
* Google Play Core (/com/google/android/play/core): NonFreeNet,NonFreeDep
```

**Device (please complete the following information):**
-  Device: n/a
-  OS: n/a
-  Version: 1.0.8

**Additional context**
Please let free software stay libre :pray:

**Comment by fartem** [comment]
@IzzySoft I'm separating build for GitHub (and other non Google Play sources) in few days.

**Comment by IzzySoft** [comment]
Thanks! So the next version should solve this then? To make sure, please let me know here when it's attached to releases so I can cross-check.

**Comment by fartem** [comment]
@IzzySoft Ok.

**Comment by fartem** [comment]
Closed because the app going to the Archive.
