### ISSUE TITLE
Create `default` and `googlePlay` flavors

### ISSUE THREAD

**Issue by fartem** [hash-checker/hash-checker-lite#79]
Create flavors and separate Google Play specific logic (in-app updates) by flavors (in-app updated should be only in `googlePlay` flavor).

**Comment by vipozdn** [comment]
Hi! creating flavors provides options: 
1) assign the same applicationId value to all variants and give each variant a different versionCode or 
2) assign a different applicationId
3) leave default id (it will be as in defaultConfig)

Should we use flavorDimension? (probavle name "distribute-version")
flavor names will be: default and googlePlay

We will also need to create source sets (basic functionality in the main/ source set + use product flavor source sets)

[link](https://developer.android.com/studio/build/build-variants#product-flavors)

After all, assign this to me pls (in both projects)

**Comment by fartem** [comment]
@vipozdn Hi. All parameters must be the same. Flavors feature needs for separating Google Play libraries from "open source" version. App publishing in other stores (and I'm planing add it to F-Droid), and these stores not applying builds with Google libraries.
